name: Deploy WordPress Theme

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.0.0
        with:
          server: 217.21.94.73  # Your Hostinger FTP server
          username: u832836407.elitetalentseekers.com  # Your FTP username
          password: Simple@123  # Use GitHub Secrets for security
          local-dir: ./
          server-dir: /public_html/wp-content/themes/elite-talent-seekers/
